# Initial content coming from
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
# exclude: ^(data/|patchassist/patchassist_tickets/templates/mail/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .gitignore
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      ## Disabled because it compains about additional modules used in testing
      #-   id: name-tests-test
      #    args: ['--django']
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: file-contents-sorter
      - id: forbid-new-submodules
      - id: mixed-line-ending
        exclude: .gitignore
      - id: pretty-format-json
        args: ["--autofix"]
      - id: sort-simple-yaml

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=120"]

  # ruff is a replacement for flake8
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.3.3
    hooks:
      - id: validate_manifest

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.0.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        # args: [--show-error-codes]
        # args: [--check-untyped-defs]
        additional_dependencies: [types-all, types-attrs]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0 # or specific git tag
    hooks:
      - id: shfmt

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        exclude: ^tests/

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.7.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
        exclude: ^CHANGELOG\.md
        exclude_types: [html]
        # stages: [commit]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.32.1
    hooks:
      - id: djlint-django
        args: ["--reformat"]
        name: djLint for Django - reformatter
      - id: djlint-django
# end
